# Generated by Django 5.1.2 on 2024-10-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageField",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to=None)),
            ],
        ),
    ]
