# Generated by Django 5.1.3 on 2024-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_method_imagemodel_form_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="encrypt",
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
