# Generated by Django 5.1.3 on 2024-12-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_imagemodel_encrypt_imagemodel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("secret_key", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zodiac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="img_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "zodiac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.zodiac"
                    ),
                ),
            ],
        ),
    ]
